;;;###autoload
(define-minor-mode apl-keys-mode
"Map APL key chords based on those used in tryapl.org/"
  :lighter " apl"
  :keymap (let ((map (make-sparse-keymap)))
            (define-key map (kbd "C-c `-") (kbd "×"))
            (define-key map (kbd "C-c `=") (kbd "÷"))
            (define-key map (kbd "C-c `j") (kbd "∘"))
            (define-key map (kbd "C-c `m") (kbd "∣"))
            (define-key map (kbd "C-c `t") (kbd "∼"))
            (define-key map (kbd "C-c `8") (kbd "≠"))
            (define-key map (kbd "C-c `4") (kbd "≤"))
            (define-key map (kbd "C-c `6") (kbd "≥"))
            (define-key map (kbd "C-c `!") (kbd "⌶"))
            (define-key map (kbd "C-c `p") (kbd "⋆"))
            (define-key map (kbd "C-c `*") (kbd "⍟"))
            (define-key map (kbd "C-c `%") (kbd "⌽"))
            (define-key map (kbd "C-c `^") (kbd "⍉"))
            (define-key map (kbd "C-c `,") (kbd "⍝"))
            (define-key map (kbd "C-c `<") (kbd "⍪"))
            (define-key map (kbd "C-c `}") (kbd "⍬"))
            (define-key map (kbd "C-c `[") (kbd "←"))
            (define-key map (kbd "C-c `y") (kbd "↑"))
            (define-key map (kbd "C-c `u") (kbd "↓"))
            (define-key map (kbd "C-c `g") (kbd "∇"))
            (define-key map (kbd "C-c `0") (kbd "∧"))
            (define-key map (kbd "C-c `9") (kbd "∨"))
            (define-key map (kbd "C-c `c") (kbd "∩"))
            (define-key map (kbd "C-c `v") (kbd "∪"))
            (define-key map (kbd "C-c `s") (kbd "⌈"))
            (define-key map (kbd "C-c `d") (kbd "⌊"))
            (define-key map (kbd "C-c `n") (kbd "⊤"))
            (define-key map (kbd "C-c `b") (kbd "⊥"))
            (define-key map (kbd "C-c `z") (kbd "⊂"))
            (define-key map (kbd "C-c `x") (kbd "⊃"))
            (define-key map (kbd "C-c `/") (kbd "⌿"))
            (define-key map (kbd "C-c `$") (kbd "⍋"))
            (define-key map (kbd "C-c `#") (kbd "⍒"))
            (define-key map (kbd "C-c `;") (kbd "⍎"))
            (define-key map (kbd "C-c `'") (kbd "⍕"))
            (define-key map (kbd "C-c `(") (kbd "⍱"))
            (define-key map (kbd "C-c `)") (kbd "⍲"))
            (define-key map (kbd "C-c `o") (kbd "○"))
            (define-key map (kbd "C-c `i") (kbd "⍳"))
            (define-key map (kbd "C-c `r") (kbd "⍴"))
            (define-key map (kbd "C-c `w") (kbd "⍵"))
            (define-key map (kbd "C-c `a") (kbd "⍺"))
            (define-key map (kbd "C-c `e") (kbd "∊"))
            (define-key map (kbd "C-c `E") (kbd "⍷"))
            (define-key map (kbd "C-c `I") (kbd "⍸"))
            (define-key map (kbd "C-c `P") (kbd "⍣"))
            (define-key map (kbd "C-c `J") (kbd "⍤"))
            (define-key map (kbd "C-c `T") (kbd "⍨"))
            (define-key map (kbd "C-c ``d") (kbd "⎕"))
            (define-key map (kbd "C-c `?") (kbd "⍠"))
            (define-key map (kbd "C-c `L") (kbd "⌷"))
            (define-key map (kbd "C-c `K") (kbd "⌸"))
            (define-key map (kbd "C-c `+") (kbd "⌹"))
            (define-key map (kbd "C-c `~") (kbd "⌺"))
            map))
;;;###autoload
(add-hook 'text-mode-hook 'apl-keys-mode)

(provide 'apl-keys-mode)
